apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: only-allow-from-pitstop-ns
  namespace: pitstop
spec:
  selector:
    matchLabels:
      app: customermanagementapi
  action: DENY
  rules:
  - from:
    - source:
        notNamespaces: ["pitstop"]
    to:
    - operation:
        ports: ["5100"]
        methods: ["*"]